In [1]:
import pandas as pd
import os
import hashlib

In [2]:
def remove_unecessary_header_text(df, file):
    is_start_of_table = df.apply(lambda row: row.astype(str).str.contains('BOROUGH').any(), axis=1)
    header_idx = df.index[is_start_of_table][0]
    df = pd.read_excel(file, skiprows = header_idx + 1)
    df.columns = df.columns.str.replace('\n', ' ').str.strip()
    df.columns = df.columns.str.replace('\s+', ' ', regex=True)
    cols = list(df.columns)
    cols[3] = "TAX CLASS BEFORE SALE" 
    cols[7] = "BUILDING CLASS BEFORE SALE"
    df.columns = cols
    return df

In [30]:
def convert_borough_to_name(borough):
    if (borough == 1):
        return "Manhattan"
    elif (borough == 2):
        return "Bronx"
    elif (borough == 3):
        return "Brooklyn"
    elif (borough == 4):
        return "Queens"
    return "Staten Island"

In [4]:
df = pd.DataFrame()
for (dirpath, dirnames, filenames) in os.walk('./'):
    for filename in filenames:
        if filename.endswith('.xls') or filename.endswith('.xlsx'): 
            cur_df = remove_unecessary_header_text(pd.read_excel(filename), filename)
            df = pd.concat([df, cur_df])

In [5]:
df.columns

Index(['BOROUGH', 'NEIGHBORHOOD', 'BUILDING CLASS CATEGORY',
       'TAX CLASS BEFORE SALE', 'BLOCK', 'LOT', 'EASE-MENT',
       'BUILDING CLASS BEFORE SALE', 'ADDRESS', 'APARTMENT NUMBER', 'ZIP CODE',
       'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'TOTAL UNITS',
       'LAND SQUARE FEET', 'GROSS SQUARE FEET', 'YEAR BUILT',
       'TAX CLASS AT TIME OF SALE', 'BUILDING CLASS AT TIME OF SALE',
       'SALE PRICE', 'SALE DATE'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 219728 entries, 0 to 12670
Data columns (total 21 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   BOROUGH                         219727 non-null  float64
 1   NEIGHBORHOOD                    219727 non-null  object
 2   BUILDING CLASS CATEGORY         219727 non-null  object
 3   TAX CLASS BEFORE SALE           219536 non-null  object
 4   BLOCK                           219727 non-null  float64
 5   LOT                             219727 non-null  float64
 6   EASE-MENT                       118428 non-null  object
 7   BUILDING CLASS BEFORE SALE      219536 non-null  object
 8   ADDRESS                         219727 non-null  object
 9   APARTMENT NUMBER                144709 non-null  object
 10  ZIP CODE                        219713 non-null  float64
 11  RESIDENTIAL UNITS               193986 non-null  float64
 12  COMMERCIAL UNITS                187522 non-null  float64
 13  TOTAL UNITS                     194718 non-null  float64
 14  LAND SQUARE FEET                186790 non-null  float64
 15  GROSS SQUARE FEET               186790 non-null  float64
 16  YEAR BUILT                      211900 non-null  float64
 17  TAX CLASS AT TIME OF SALE       219727 non-null  float64
 18  BUILDING CLASS AT TIME OF SALE  219727 non-null  object
 19  SALE PRICE                      219727 non-null  float64
 20  SALE DATE                       219727 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(12), object(8)
memory usage: 36.9+ MB

In [7]:
df.head()

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS BEFORE SALE,BLOCK,LOT,EASE-MENT,BUILDING CLASS BEFORE SALE,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,2.0,BATHGATE,01 ONE FAMILY DWELLINGS,1,3030.0,70.0,NaN,A1,4445 PARK AVENUE,NaN,...,1.0,0.0,1.0,1694.0,1497.0,1899.0,1.0,A1,388500.0,2019-07-23
1,2.0,BATHGATE,01 ONE FAMILY DWELLINGS,1,3039.0,29.0,NaN,A9,2327 WASHINGTON AVENUE,NaN,...,1.0,0.0,1.0,1095.0,1260.0,1910.0,1.0,A9,110000.0,2019-12-06
2,2.0,BATHGATE,01 ONE FAMILY DWELLINGS,1,3043.0,55.0,NaN,A1,1948 BATHGATE AVENUE,NaN,...,1.0,0.0,1.0,2356.0,2047.0,1901.0,1.0,A1,470000.0,2019-03-08
3,2.0,BATHGATE,01 ONE FAMILY DWELLINGS,1,3046.0,39.0,NaN,A1,2075 BATHGATE AVENUE,NaN,...,1.0,0.0,1.0,1986.0,1344.0,1899.0,1.0,A1,420000.0,2019-05-24
4,2.0,BATHGATE,02 TWO FAMILY DWELLINGS,1,2912.0,137.0,NaN,B1,496 CLAREMONT PARKWAY,NaN,...,2.0,0.0,2.0,2000.0,2400.0,1993.0,1.0,B1,0.0,2019-06-12

In [8]:
df.shape

(219728, 21)

In [9]:
df.head()

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS BEFORE SALE,BLOCK,LOT,EASE-MENT,BUILDING CLASS BEFORE SALE,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,2.0,BATHGATE,01 ONE FAMILY DWELLINGS,1,3030.0,70.0,NaN,A1,4445 PARK AVENUE,NaN,...,1.0,0.0,1.0,1694.0,1497.0,1899.0,1.0,A1,388500.0,2019-07-23
1,2.0,BATHGATE,01 ONE FAMILY DWELLINGS,1,3039.0,29.0,NaN,A9,2327 WASHINGTON AVENUE,NaN,...,1.0,0.0,1.0,1095.0,1260.0,1910.0,1.0,A9,110000.0,2019-12-06
2,2.0,BATHGATE,01 ONE FAMILY DWELLINGS,1,3043.0,55.0,NaN,A1,1948 BATHGATE AVENUE,NaN,...,1.0,0.0,1.0,2356.0,2047.0,1901.0,1.0,A1,470000.0,2019-03-08
3,2.0,BATHGATE,01 ONE FAMILY DWELLINGS,1,3046.0,39.0,NaN,A1,2075 BATHGATE AVENUE,NaN,...,1.0,0.0,1.0,1986.0,1344.0,1899.0,1.0,A1,420000.0,2019-05-24
4,2.0,BATHGATE,02 TWO FAMILY DWELLINGS,1,2912.0,137.0,NaN,B1,496 CLAREMONT PARKWAY,NaN,...,2.0,0.0,2.0,2000.0,2400.0,1993.0,1.0,B1,0.0,2019-06-12

In [10]:
df_dup = df[df.duplicated()]
df_dup

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS BEFORE SALE,BLOCK,LOT,EASE-MENT,BUILDING CLASS BEFORE SALE,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
2735,2.0,KINGSBRIDGE/JEROME PARK,13 CONDOS - ELEVATOR APARTMENTS,2,5777.0,1020.0,NaN,R4,"3816 WALDO, 6C",6C,...,1.0,0.0,1.0,0.0,0.0,2004.0,2.0,R4,1.0,2019-03-31
3164,2.0,MORRIS PARK/VAN NEST,02 TWO FAMILY DWELLINGS,1,4272.0,49.0,NaN,B3,1928 HAIGHT AVENUE,NaN,...,2.0,0.0,2.0,2500.0,1632.0,1930.0,1.0,B3,0.0,2019-07-15
4622,2.0,PELHAM PARKWAY NORTH,02 TWO FAMILY DWELLINGS,1,4453.0,29.0,NaN,B1,2446 LACONIA,NaN,...,2.0,0.0,2.0,3742.0,3085.0,1940.0,1.0,B1,0.0,2019-02-08
1240,3.0,BEDFORD STUYVESANT,02 TWO FAMILY DWELLINGS,1,1619.0,76.0,NaN,B3,575 LEXINGTON,NaN,...,2.0,0.0,2.0,2000.0,2200.0,1899.0,1.0,B3,0.0,2019-06-17
2117,3.0,BEDFORD STUYVESANT,12 CONDOS - WALKUP APARTMENTS,2,1914.0,1004.0,NaN,R2,"163 SKILLMAN STREET, 4A",4A,...,1.0,0.0,1.0,0.0,0.0,2003.0,2.0,R2,0.0,2019-03-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12013,5.0,WESTERLEIGH,01 ONE FAMILY HOMES,1,1470.0,20.0,,A1,183 GLASCOE AVENUE,,...,1.0,0.0,1.0,4500.0,900.0,1955.0,1.0,A1,0.0,2003-10-09
12174,5.0,WESTERLEIGH,21 OFFICE BUILDINGS,4,394.0,27.0,,O6,1500 FOREST AVENUE,,...,0.0,1.0,1.0,11000.0,3120.0,1965.0,4.0,O6,0.0,2003-10-30
12182,5.0,WILLOWBROOK,01 ONE FAMILY HOMES,1,730.0,61.0,,A2,91 KELL AVENUE,,...,1.0,0.0,1.0,4000.0,990.0,1955.0,1.0,A2,0.0,2003-07-08
12221,5.0,WILLOWBROOK,01 ONE FAMILY HOMES,1,775.0,66.0,,A5,30 ROOSEVELT AVENUE,,...,1.0,0.0,1.0,4725.0,1900.0,2002.0,1.0,A5,374166.0,2003-11-26
12620,5.0,WOODROW,02 TWO FAMILY HOMES,1,7091.0,190.0,,B9,628 BLOOMINGDALE ROAD,,...,2.0,0.0,2.0,3075.0,2230.0,1998.0,1.0,B9,405000.0,2003-05-15

In [11]:
df = df.drop_duplicates()

In [12]:
df_dup = df[df.duplicated()]
df_dup

Empty DataFrame
Columns: [BOROUGH, NEIGHBORHOOD, BUILDING CLASS CATEGORY, TAX CLASS BEFORE SALE, BLOCK, LOT, EASE-MENT, BUILDING CLASS BEFORE SALE, ADDRESS, APARTMENT NUMBER, ZIP CODE, RESIDENTIAL UNITS, COMMERCIAL UNITS, TOTAL UNITS, LAND SQUARE FEET, GROSS SQUARE FEET, YEAR BUILT, TAX CLASS AT TIME OF SALE, BUILDING CLASS AT TIME OF SALE, SALE PRICE, SALE DATE]
Index: []

[0 rows x 21 columns]

In [13]:
df.shape

(218227, 21)

In [14]:

df['APARTMENT NUMBER'].dtype

dtype('O')

In [15]:
df_dup = df[df.duplicated()]
df_dup

Empty DataFrame
Columns: [BOROUGH, NEIGHBORHOOD, BUILDING CLASS CATEGORY, TAX CLASS BEFORE SALE, BLOCK, LOT, EASE-MENT, BUILDING CLASS BEFORE SALE, ADDRESS, APARTMENT NUMBER, ZIP CODE, RESIDENTIAL UNITS, COMMERCIAL UNITS, TOTAL UNITS, LAND SQUARE FEET, GROSS SQUARE FEET, YEAR BUILT, TAX CLASS AT TIME OF SALE, BUILDING CLASS AT TIME OF SALE, SALE PRICE, SALE DATE]
Index: []

[0 rows x 21 columns]

In [16]:
df['YEAR BUILT'].value_counts()

YEAR BUILT
1920.0    17388
1930.0    13480
0.0       13477
1925.0    11811
1910.0    10089
          ...
1842.0        1
1841.0        1
1835.0        1
1834.0        1
1862.0        1
Name: count, Length: 195, dtype: int64

In [17]:
df['COMMERCIAL UNITS'] = df['COMMERCIAL UNITS'].fillna(0)
df['RESIDENTIAL UNITS'] = df['RESIDENTIAL UNITS'].fillna(0)
df['LAND SQUARE FEET'] = df['LAND SQUARE FEET'].fillna(0)
df['GROSS SQUARE FEET'] = df['GROSS SQUARE FEET'].fillna(0)
df['TOTAL UNITS'] = df['TOTAL UNITS'].fillna(0)
df['TAX CLASS BEFORE SALE'] = df['TAX CLASS BEFORE SALE'].fillna('unknown')
df['BUILDING CLASS BEFORE SALE'] = df['BUILDING CLASS BEFORE SALE'].fillna('unknown')
df['TAX CLASS AT TIME OF SALE'] = df['TAX CLASS AT TIME OF SALE'].fillna('unknown')
df['BUILDING CLASS AT TIME OF SALE'] = df['BUILDING CLASS AT TIME OF SALE'].fillna('unknown')
df['APARTMENT NUMBER'] = df['APARTMENT NUMBER'].fillna('unknown')
df = df.loc[~(df['YEAR BUILT'].isna()) & ~(df['YEAR BUILT'] == 0)]
df = df.loc[~(df['ZIP CODE'] == 0) & ~(df['ZIP CODE'].isna())]

In [18]:
df['COMMERCIAL UNITS'] = df['COMMERCIAL UNITS'].astype('int32')
df['RESIDENTIAL UNITS'] = df['RESIDENTIAL UNITS'].astype('int32')
df['LAND SQUARE FEET'] = df['LAND SQUARE FEET'].astype('float')
df['GROSS SQUARE FEET'] = df['GROSS SQUARE FEET'].astype('float')
df['TOTAL UNITS'] = df['TOTAL UNITS'].astype('int32')
df['TAX CLASS BEFORE SALE'] = df['TAX CLASS BEFORE SALE'].astype('string')
df['BUILDING CLASS BEFORE SALE'] = df['BUILDING CLASS BEFORE SALE'].astype('string')
df['ADDRESS'] = df['ADDRESS'].astype('string')
df['APARTMENT NUMBER'] = df['APARTMENT NUMBER'].astype('string')
df['TAX CLASS AT TIME OF SALE'] = df['TAX CLASS AT TIME OF SALE'].astype('string')
df['BUILDING CLASS AT TIME OF SALE'] = df['BUILDING CLASS AT TIME OF SALE'].astype('string')

In [19]:
df = df.drop(columns=['EASE-MENT'])

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
print('null count commercial units ',df['COMMERCIAL UNITS'].isna().sum())
print('null count residential units ',df['RESIDENTIAL UNITS'].isna().sum())
print('null count land square feet ',df['LAND SQUARE FEET'].isna().sum())
print('null count gross square feet ',df['GROSS SQUARE FEET'].isna().sum())
print('null count total units feet ',df['TOTAL UNITS'].isna().sum())
print('null count total units feet ',df['BUILDING CLASS BEFORE SALE'].isna().sum())

null count commercial units  0
null count residential units  0
null count land square feet  0
null count gross square feet  0
null count total units feet  0
null count total units feet  0

In [22]:
def calculate_surrogate_key(row):
    unique_key = hashlib.md5((
        str(row['BOROUGH']) + 
        str(row['NEIGHBORHOOD']) +
        str(row['BUILDING CLASS CATEGORY']) +
        str(row['TAX CLASS BEFORE SALE']) +
        str(row['BLOCK']) + 
        str(row['LOT']) + 
        str(row['BUILDING CLASS BEFORE SALE']) +
        str(row['ADDRESS']) +
        str(row['APARTMENT NUMBER']) +
        str(row['ZIP CODE']) +
        str(row['RESIDENTIAL UNITS']) +
        str(row['COMMERCIAL UNITS']) +
        str(row['TOTAL UNITS']) +
        str(row['LAND SQUARE FEET']) +
        str(row['GROSS SQUARE FEET']) +
        str(row['YEAR BUILT']) +
        str(row['TAX CLASS AT TIME OF SALE']) + 
        str(row['BUILDING CLASS AT TIME OF SALE']) +
        str(row['SALE PRICE']) +
        str(row['SALE DATE'])
    ).encode('utf-8')).hexdigest()
    return unique_key

In [23]:
df['ID'] = df.apply(calculate_surrogate_key, axis=1).astype('string')

In [24]:
df['ID']

0        904431b05375647da5ab5b7c1533acb0
1        c39be89d6971ab01ad7ee59869f0a83a
2        4dbf0823a38729de2b26ee1c5bbf6258
3        fbca61bfa0a3a8cf0be59891478d3dd8
4        9f22a964f3e253848238b2c394867ba9
                       ...
12662    a3641dcb83e139d0b5ddefd84cd5ec43
12663    23e4ecd28dddc52b23d3d131f13cf68d
12664    bf64aada332e176a38dac173da009d33
12669    f785c045789162b08cf4acc98bb8baf3
12670    547f605ce2ee9559b575aa01aad858e2
Name: ID, Length: 196821, dtype: string

In [25]:
df.isna().sum().sum()

np.int64(0)

In [26]:
df.shape

(196821, 21)

In [27]:
df['ID'].duplicated().sum()

np.int64(0)

In [28]:
df['BOROUGH'].isna().sum()

np.int64(0)

In [31]:
df['BOROUGH'] = df['BOROUGH'].apply(convert_borough_to_name)

In [42]:
df['BOROUGH'] = df['BOROUGH'].astype('string')
df['BOROUGH'].head()

0    Bronx
1    Bronx
2    Bronx
3    Bronx
4    Bronx
Name: BOROUGH, dtype: string

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 196821 entries, 0 to 12670
Data columns (total 21 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   BOROUGH                         196821 non-null  string
 1   NEIGHBORHOOD                    196821 non-null  object
 2   BUILDING CLASS CATEGORY         196821 non-null  object
 3   TAX CLASS BEFORE SALE           196821 non-null  string
 4   BLOCK                           196821 non-null  float64
 5   LOT                             196821 non-null  float64
 6   BUILDING CLASS BEFORE SALE      196821 non-null  string
 7   ADDRESS                         196821 non-null  string
 8   APARTMENT NUMBER                196821 non-null  string
 9   ZIP CODE                        196821 non-null  float64
 10  RESIDENTIAL UNITS               196821 non-null  int32
 11  COMMERCIAL UNITS                196821 non-null  int32
 12  TOTAL UNITS                     196821 non-null  int32
 13  LAND SQUARE FEET                196821 non-null  float64
 14  GROSS SQUARE FEET               196821 non-null  float64
 15  YEAR BUILT                      196821 non-null  float64
 16  TAX CLASS AT TIME OF SALE       196821 non-null  string
 17  BUILDING CLASS AT TIME OF SALE  196821 non-null  string
 18  SALE PRICE                      196821 non-null  float64
 19  SALE DATE                       196821 non-null  datetime64[ns]
 20  ID                              196821 non-null  string
dtypes: datetime64[ns](1), float64(7), int32(3), object(2), string(8)
memory usage: 30.8+ MB